CREATE
  (Hampus)-[:OWNS]->(SafeBurn),
  (Hampus)-[:OWNS]->(FirstAid),
  (Hampus)-[:OWNS]->(Sanitation),
  (Hampus)-[:OWNS]->(Placement),
  (Hampus)-[:OWNS]->(SoundControl)
CREATE
  (Freya)-[:OWNS]->(TrackWeather),
  (Freya)-[:OWNS]->(BurnPerimeter)
CREATE
  (Vishnu)-[:OWNS]->(DisasterPlan),
  (Vishnu)-[:OWNS]->(PortopottiePlacement),
  (Vishnu)-[:OWNS]->(BookPortopotties),
  (Vishnu)-[:OWNS]->(PlacementMap),
  (Vishnu)-[:OWNS]->(SanctuaryVolunteers)
CREATE
  (Shiva)-[:OWNS]->(SoundMeasurement),
  (Shiva)-[:OWNS]->(SoundCurfewPlanning)

CREATE
  (TrackWeather)-[:FULFILLS]->(SafeBurn),
  (BurnPerimeter)-[:FULFILLS]->(SafeBurn),
  (SanctuaryVolunteers)-[:FULFILLS]->(FirstAid),
  (DisasterPlan)-[:FULFILLS]->(FirstAid),
  (PortopottiePlacement)-[:FULFILLS]->(Sanitation),
  (BookPortopotties)-[:FULFILLS]->(Sanitation),
  (PlacementMap)-[:FULFILLS]->(Placement),
  (SoundMeasurement)-[:FULFILLS]->(SoundControl),
  (SoundCurfewPlanning)-[:FULFILLS]->(SoundControl)

CREATE
  (SafeBurn)-[:RELATES_TO]->(DisasterPlan),
  (DisasterPlan)-[:RELATES_TO]->(SanctuaryVolunteers),
  (PlacementMap)-[:RELATES_TO]->(SoundCurfewPlanning),
  (PortopottiePlacement)-[:RELATES_TO]->(PlacementMap)
