CREATE
  (Hampus)-[:REALIZES]->(PlacementMap),
  (Hampus)-[:GUIDES]->(SafeBurn),
  (Hampus)-[:GUIDES]->(FirstAid),
  (Hampus)-[:GUIDES]->(Sanitation),
  (Hampus)-[:GUIDES]->(Placement),
  (Hampus)-[:GUIDES]->(SoundControl)
CREATE
  (Freya)-[:REALIZES]->(SanctuaryVolunteers),
  (Freya)-[:GUIDES]->(TrackWeather),
  (Freya)-[:GUIDES]->(BurnPerimeter)
CREATE
  (Vishnu)-[:GUIDES]->(DisasterPlan),
  (Vishnu)-[:GUIDES]->(PortopottiePlacement),
  (Vishnu)-[:GUIDES]->(BookPortopotties),
  (Vishnu)-[:GUIDES]->(PlacementMap),
  (Vishnu)-[:GUIDES]->(SanctuaryVolunteers)
CREATE
  (Shiva)-[:REALIZES]->(DisasterPlan),
  (Shiva)-[:REALIZES]->(FirstAid),
  (Shiva)-[:GUIDES]->(SoundMeasurement),
  (Shiva)-[:GUIDES]->(SoundCurfewPlanning)

CREATE
  (TrackWeather)-[:FULFILLS]->(SafeBurn),
  (BurnPerimeter)-[:FULFILLS]->(SafeBurn),
  (SanctuaryVolunteers)-[:FULFILLS]->(FirstAid),
  (DisasterPlan)-[:FULFILLS]->(FirstAid),
  (PortopottiePlacement)-[:FULFILLS]->(Sanitation),
  (BookPortopotties)-[:FULFILLS]->(Sanitation),
  (PlacementMap)-[:FULFILLS]->(Placement),
  (SoundMeasurement)-[:FULFILLS]->(SoundControl),
  (SoundCurfewPlanning)-[:FULFILLS]->(SoundControl)

CREATE
  (SafeBurn)-[:RELATES_TO]->(DisasterPlan),
  (DisasterPlan)-[:RELATES_TO]->(SanctuaryVolunteers),
  (PlacementMap)-[:RELATES_TO]->(SoundCurfewPlanning),
  (PortopottiePlacement)-[:RELATES_TO]->(PlacementMap)
